services:
  mongo:
    image: mongo:6
    container_name: mongo_container
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: taskdb
  app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      - mongo
    ports:
      - '${PORT}:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: ['sh', '-c', 'sleep 5 && npm run start']

volumes:
  mongo_data:
