services:
  mongo:
    image: mongo:6
    container_name: mongo_container
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: taskdb
    networks:
      - mongo-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mongo-network
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017/taskdb?authSource=admin
    # restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    depends_on:
      test:
        condition: service_completed_successfully
      mongo:
        condition: service_healthy
    networks:
      - mongo-network
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://root:password@mongo:27017/taskdb?authSource=admin
    ports:
      - "3000:3000"
    restart: always

volumes:
  mongo_data:

networks:
  mongo-network:
    driver: bridge
